(library
 (name bindings)
 (public_name arrow.bindings)
 (modules bindings)
 (libraries ctypes ctypes.stubs))

(executable
 (public_name gen)
 (package arrow)
 (name gen)
 (modules gen)
 (libraries ctypes.stubs bindings))

(library
 (name arrow_stubs)
 (public_name arrow.stubs)
 (modules)
 (libraries ctypes))
