(executable
 (name discover)
 (modules discover)
 (libraries dune-configurator))

(rule
 (targets c_flags.sexp c_library_flags.sexp)
 (deps (:discover discover.exe))
 (action (run %{discover})))

(library
 (public_name arrow)
 (name arrow)
 (modules arrow builder c_api c_wrapper column compression
          io parquet parquet_reader schema table time type valid
          bindings bindings_generated parquet_bindings parquet_bindings_generated)
 (libraries ctypes ctypes.foreign ptime arrow.bindings arrow.parquet.bindings)
 (private_modules c_wrapper bindings_generated parquet_bindings_generated parquet_bindings)
 (foreign_stubs
  (language c)
  (names arrow_c_api_stubs parquet_c_stubs)
  (flags (:include c_flags.sexp)))
 (foreign_stubs
  (language cxx)
  (names arrow_c_api parquet_stubs)
  (flags :standard -std=c++17 (:include c_flags.sexp)))
 (c_library_flags (:include c_library_flags.sexp)))

(rule
 (targets bindings.ml)
 (deps stubs/bindings.ml)
 (action
  (copy stubs/bindings.ml bindings.ml)))

(rule
 (targets arrow_c_api_stubs.c bindings_generated.ml)
 (deps
  (:gen stubs/gen.exe))
 (action
  (run %{gen})))

(rule
 (targets parquet_bindings.ml)
 (deps parquet/stubs/parquet_bindings.ml)
 (action
  (copy parquet/stubs/parquet_bindings.ml parquet_bindings.ml)))

(rule
 (targets parquet_c_stubs.c parquet_bindings_generated.ml)
 (deps
  (:gen parquet/stubs/gen.exe))
 (action
  (run %{gen})))
